name: HTML Static Site Deploy with Backup

on:
  push:
    branches: [master]

jobs:
  deploy-static-site:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create timestamp for backup
      shell: powershell
      run: |
        $ts = Get-Date -Format 'yyyyMMdd_HHmmss'
        echo "TIMESTAMP=$ts" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Backup previous commit files before deploy
      shell: powershell
      run: |
          $ts = Get-Date -Format 'yyyyMMdd_HHmmss'
          $backupPath = "C:\Users\manoj\Deployments\repo-backup_$ts"
          git checkout HEAD~1
          New-Item -Path $backupPath -ItemType Directory -Force | Out-Null
          Copy-Item -Path ".\*" -Destination $backupPath -Recurse -Force
          git checkout -
          Write-Host "Previous commit files backed up to $backupPath"
      
    - name: Deploy new static files to IIS
      shell: powershell
      run: |
        $deployPath = "C:\inetpub\wwwroot\YourApp"
        if (Test-Path $deployPath) {
          Remove-Item -Path $deployPath -Recurse -Force
        }
        New-Item -Path $deployPath -ItemType Directory -Force | Out-Null
        Copy-Item -Path ".\*" -Destination $deployPath -Recurse -Force
        Write-Host "Deployment completed to $deployPath"
