name: HTML Static Site Deploy with Backup

on:
  push:
    branches: [master]

jobs:
  deploy-static-site:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create timestamp for backup
      shell: powershell
      run: |
        $ts = Get-Date -Format 'yyyyMMdd_HHmmss'
        echo "TIMESTAMP=$ts" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Backup current deployed site
      shell: powershell
      run: |
        $deployPath = "C:\inetpub\wwwroot\YourApp"
        $backupPath = "C:\Users\manoj\Deployments\backup\backup_$env:TIMESTAMP"

        if (Test-Path $deployPath) {
          New-Item -Path $backupPath -ItemType Directory -Force | Out-Null
          Copy-Item -Path "$deployPath\*" -Destination $backupPath -Recurse -Force
          Write-Host "Backup completed to $backupPath"
        } else {
          Write-Host "No existing deployment to back up."
        }

    - name: Deploy new static files to IIS
      shell: powershell
      run: |
        $deployPath = "C:\inetpub\wwwroot\YourApp"
        if (Test-Path $deployPath) {
          Remove-Item -Path $deployPath -Recurse -Force
        }
        New-Item -Path $deployPath -ItemType Directory -Force | Out-Null
        Copy-Item -Path ".\*" -Destination $deployPath -Recurse -Force
        Write-Host "Deployment completed to $deployPath"
