name: HTML Static Site Deploy with Backup

on:
  push:
    branches: [master]

jobs:
  deploy-static-site:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create timestamp for backup
      shell: pwsh
      run: |
        $ts = Get-Date -Format 'yyyyMMdd_HHmmss'
        echo "TIMESTAMP=$ts" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Backup current deployed site
      shell: cmd
      run: |
        if exist "C:\inetpub\wwwroot\YourApp" (
          mkdir "C:\Users\manoj\Deployments\backup\backup_%TIMESTAMP%"
          xcopy "C:\inetpub\wwwroot\YourApp\*" "C:\Users\manoj\Deployments\backup\backup_%TIMESTAMP%\" /s /e /y /i
        ) else (
          echo No existing deployment to back up.
        )

    - name: Deploy new static files to IIS
      shell: cmd
      run: |
        rmdir /s /q "C:\inetpub\wwwroot\YourApp"
        mkdir "C:\inetpub\wwwroot\YourApp"
        xcopy ".\*" "C:\inetpub\wwwroot\YourApp\" /s /e /y /i
