name: Deploy Static Site via SFTP

on:
  push:
    branches:
      - master  # or main, depending on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Backup Existing Server Files
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        script: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          BACKUP_DIR="/var/www/html_backup_$TIMESTAMP"
          echo "Backing up current site to $BACKUP_DIR"
          cp -r /var/www/html "$BACKUP_DIR"

    - name: Deploy Files via SFTP
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        source: "*"
        target: "/var/www/html"
